console.log('start');

throw new Error('uh oh!');

console.log('end');

// try {
//   const x = undefined;
//   console.log(x.foo());
// }
// catch (error) {
//   console.error('caught error: ', error.message)
// }

